# Generated by Django 4.0.6 on 2022-07-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Response',
        ),
    ]
